-- 코드를 작성해주세요

WITH TEST AS (
    SELECT 
    PARENT_ID
    , COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)

SELECT ID, IFNULL(CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN TEST AS C
    ON E.ID = C.PARENT_ID;