-- 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차
-- 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 출력
-- 특정 월의 총 대여 횟수가 0인 경우 제외
SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE MONTH(START_DATE) BETWEEN 8 AND 10 AND CAR_ID IN (
    SELECT CAR_ID FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10 
    GROUP BY CAR_ID 
    HAVING COUNT(CAR_ID) >= 5) 
GROUP BY MONTH(START_DATE), CAR_ID 
ORDER BY MONTH, CAR_ID DESC;