SELECT DISTINCT(H.CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  H
        LEFT JOIN  CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    WHERE DATE_FORMAT(START_DATE, "%Y-%m") = '2022-10'
    AND CAR_TYPE = '세단'
    ORDER BY CAR_ID DESC